name: audio_control

services:
  audio_ctl:
    build:
      context: /home/ulink/audio-pro
      dockerfile: /home/ulink/audio-pro/Dockerfile_ctl
      
    image: audio-ctl:${TAGVERSION}
    container_name: audio-ctl

    command: ["python", "audio_control.py"]
    ports:
      - "5003:5003"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /run/user/1000/pulse:/run/user/1000/pulse
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/ulink/audio-pro/docker-compose_services.yml:/usr/src/app/docker-compose_services.yml
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PULSE_SERVER=unix:/run/user/1000/pulse/native
      - TAGVERSION=${TAGVERSION}
    restart: unless-stopped