name: audio_control

services:
  audio_ctl:
    build:
      context: ~/audio-pro
      dockerfile: /mnt/audio-pro/Dockerfile_ctl
      
    image: audio-ctl:latest
    container_name: audio_ctl

    command: ["python", "audio_control.py"]
    ports:
      - "5003:5003"
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - /run/user/${UID}/pulse:/run/user/${UID}/pulse
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/audio-pro/docker-comose_services.yaml:/usr/src/app/docker-comose_services.yaml
    environment:
      - PULSE_SERVER=unix:/run/user/${UID}/pulse/native
    restart: unless-stopped